export const ACTIVITY_PREVIEW_ROWS_PER_CARD = 3;
export const ACTIVITY_PREVIEW_VERTICAL_SPAN = 3;
export const ACTIVITY_PREVIEW_LIMIT =
  ACTIVITY_PREVIEW_ROWS_PER_CARD * ACTIVITY_PREVIEW_VERTICAL_SPAN;
